version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    depends_on:
      mongo:
        condition: service_started
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload-demo
      PAYLOAD_SECRET: your-super-secret-key-here
      NEXT_PUBLIC_SERVER_URL: http://localhost:3000
      PAYLOAD_PUBLIC_SERVER_URL: http://localhost:3000
      NODE_ENV: development
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    logging:
      driver: none

volumes:
  node_modules:
  mongodb_data:
